name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Install Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible
        
    - name: Syntax check
      run: ansible-playbook --syntax-check site.yml