name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint Ansible Playbooks
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible ansible-lint yamllint
        
    - name: Lint YAML files
      run: |
        yamllint .
        
    - name: Lint Ansible playbooks
      run: |
        ansible-lint site.yml
        
    - name: Syntax check
      run: |
        ansible-playbook --syntax-check site.yml

  test:
    runs-on: ubuntu-latest
    name: Test Installation
    needs: lint
    
    strategy:
      matrix:
        ubuntu-version: ['20.04', '22.04', '24.04']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up test environment
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible
        
    - name: Run syntax validation
      run: |
        ./tests/validate-syntax.sh
        
    - name: Test role validation
      run: |
        ./tests/test-roles.sh
        
    - name: Dry run installation
      run: |
        ansible-playbook site.yml --check --diff

  test-interactive:
    runs-on: ubuntu-latest
    name: Test Interactive Setup
    needs: lint
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Test setup script syntax
      run: |
        bash -n setup.sh
        
    - name: Test setup script help
      run: |
        # Test that the script doesn't fail on basic checks
        sudo apt-get update
        sudo apt-get install -y whiptail
        
        # Mock the interactive parts for testing
        export DEBIAN_FRONTEND=noninteractive
        timeout 10 bash setup.sh || true